#!/usr/bin/env php
<?php

/*
 * This file is part of the Slim API skeleton package
 *
 * Copyright (c) 2016 Mika Tuupola
 *
 * Licensed under the MIT license:
 *   http://www.opensource.org/licenses/mit-license.php
 *
 * Project home:
 *   https://github.com/tuupola/slim-api-skeleton
 *
 */

date_default_timezone_set("UTC");

#error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);

require __DIR__ . "/vendor/autoload.php";

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

/* Setup Slim */
$app = new Slim\App();
$container = $app->getContainer();

require __DIR__ . "/api/config/dependencies.php";

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use App\Cron;

$console = new Application();

$console
    ->register("migrate")
    ->setDescription("Migrate database tables")
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($container) {
        print "Migrating database...\n";
        $container["spot"]->mapper("App\Config")->migrate();
        $container["spot"]->mapper("App\User")->migrate();
        $container["spot"]->mapper("App\Dealer")->migrate();
        $container["spot"]->mapper("App\Email")->migrate();
        $container["spot"]->mapper("App\ThemeType")->migrate();
        $container["spot"]->mapper("App\ThemeSection")->migrate();
        $container["spot"]->mapper("App\ThemePosition")->migrate();
        $container["spot"]->mapper("App\Product")->migrate();
        $container["spot"]->mapper("App\Service")->migrate();
        $container["spot"]->mapper("App\Post")->migrate();
        $container["spot"]->mapper("App\Lead")->migrate();
        $container["spot"]->mapper("App\VisitSchedule")->migrate();
    });

$console
    ->register("seed")
    ->setDescription("Seed database")
    ->setCode(function (InputInterface $input, OutputInterface $output) use ($container) {
        print "Seeding database...\n";
        Cron::seed();
    });

$console->run();